### ISSUE TITLE
Hand-picked features don't play nice with the `attributes` feature

### ISSUE THREAD

**Issue by c410-f3r** [async-rs/async-std#868]
Discovered while I was trying to decrease the amount of transient dependencies through features.

If the same set of features within `default` is explicit declared:

https://github.com/async-rs/async-std/blob/bd297473ccf6d19deca91f47e055ec67be906ee2/Cargo.toml#L25-L36

```toml
[dev-dependencies]
async-std = { default-features = false, features = ["attributes", "std", "async-executor", "async-io", "async-task", "blocking", "futures-lite", "kv-log-macro", "log", "num_cpus", "pin-project-lite"], version = "1.0" }
```

`#[async_std::test]` will complain about missing functions when it really shouldn't:

```
#[async_std::test]
  ^^^^^^^^^^^^^^^^^^ not found in `async_std::task`
```

This also implies that a bare-minimal set of features for a working executor isn't an option, leaving `default` as the only possible way.
