### ISSUE TITLE
Linker error in stable-x86_64-pc-windows-gnu toolchain

### ISSUE THREAD

**Issue by yatesco** [async-rs/async-std#898]
Hi there, including `async-std#1.6.5` pulls in `async-io#1.10.0` which can't be cross compiled due to https://github.com/stjepang/async-io/issues/16

```bash
session_db v0.1.0 (/Users/coliny/Dev/com.qfi.health/src/rust-tools/session_db)
├── async-std v1.6.5
<snip>
│   ├── async-global-executor v1.4.2
<snip>
│   │   ├── async-io v1.1.10
```

It is claimed that this issue is fixed (https://github.com/stjepang/async-io/issues/16#issuecomment-692170201) but I still get the error.

Is there any magic I can use to tell `async-std` to pull in the "fixed" version of `async-io`?

Thanks!

**Comment by Licenser** [comment]
could the patch option for cargo help here?

```toml
[patch.crates-io]
async-std = { git = 'https://github.com/async-rs/async-std', branch = 'master',  features = ['attributes']}
```

src:  https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#using-patch-with-multiple-versions
